#!/bin/bash
echo "🧪 Testing Twitch General-Only Filter"
echo "===================================="
echo ""
echo "With the new configuration:"
echo ""
echo "✅ WILL appear in Twitch:"
echo "  • Messages from Discord #general"
echo "  • Messages from Telegram general topic"
echo ""
echo "❌ Will NOT appear in Twitch:"
echo "  • Messages from Discord #vent"
echo "  • Messages from Discord #test"
echo "  • Messages from Discord #dev"
echo "  • Messages from Discord #music"
echo "  • Messages from Discord #art"
echo "  • Messages from Discord #pets"
echo "  • Messages from any Telegram topic"
echo ""
echo "To test:"
echo "1. Send 'Hello from general' in Discord #general"
echo "   → Should appear in Twitch chat"
echo ""
echo "2. Send 'Hello from test' in Discord #test"
echo "   → Should NOT appear in Twitch chat"
echo "   → Check logs for: 'Skipping test message to Twitch - only general channel is relayed'"
echo ""
echo "All Discord ↔ Telegram routing continues to work normally!"